# Generated by Django 2.2.7 on 2019-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
                ('state', models.IntegerField()),
                ('intent', models.CharField(max_length=32)),
                ('addition', models.CharField(max_length=32)),
                ('timestep', models.IntegerField()),
            ],
        ),
    ]
