# Generated by Django 2.2.7 on 2019-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20191128_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='addition',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='answer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='intent',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
