# Generated by Django 2.2.7 on 2019-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_auto_20191128_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='addition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='answer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='intent',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
